import Foundation

public enum Scopes: String, CustomStringConvertible {
    case sessionsWrite = "sessions.write"
    case usersRead = "users.read"
    case usersWrite = "users.write"
    case teamsRead = "teams.read"
    case teamsWrite = "teams.write"
    case databasesRead = "databases.read"
    case databasesWrite = "databases.write"
    case collectionsRead = "collections.read"
    case collectionsWrite = "collections.write"
    case tablesRead = "tables.read"
    case tablesWrite = "tables.write"
    case attributesRead = "attributes.read"
    case attributesWrite = "attributes.write"
    case columnsRead = "columns.read"
    case columnsWrite = "columns.write"
    case indexesRead = "indexes.read"
    case indexesWrite = "indexes.write"
    case documentsRead = "documents.read"
    case documentsWrite = "documents.write"
    case rowsRead = "rows.read"
    case rowsWrite = "rows.write"
    case filesRead = "files.read"
    case filesWrite = "files.write"
    case bucketsRead = "buckets.read"
    case bucketsWrite = "buckets.write"
    case functionsRead = "functions.read"
    case functionsWrite = "functions.write"
    case sitesRead = "sites.read"
    case sitesWrite = "sites.write"
    case logRead = "log.read"
    case logWrite = "log.write"
    case executionRead = "execution.read"
    case executionWrite = "execution.write"
    case localeRead = "locale.read"
    case avatarsRead = "avatars.read"
    case healthRead = "health.read"
    case providersRead = "providers.read"
    case providersWrite = "providers.write"
    case messagesRead = "messages.read"
    case messagesWrite = "messages.write"
    case topicsRead = "topics.read"
    case topicsWrite = "topics.write"
    case subscribersRead = "subscribers.read"
    case subscribersWrite = "subscribers.write"
    case targetsRead = "targets.read"
    case targetsWrite = "targets.write"
    case rulesRead = "rules.read"
    case rulesWrite = "rules.write"
    case migrationsRead = "migrations.read"
    case migrationsWrite = "migrations.write"
    case vcsRead = "vcs.read"
    case vcsWrite = "vcs.write"
    case assistantRead = "assistant.read"
    case tokensRead = "tokens.read"
    case tokensWrite = "tokens.write"

    public var description: String {
        return rawValue
    }
}
